eureka:
  instance:
    hostName: uapay.uarocky.com
    nonSecurePort: 80
    preferIpAddress: true
    ipAddress: ${eureka.instance.hostName}
    instance-id: http://${eureka.instance.ipAddress}/SoutheastAsia-payment-center/
    health-check-url: http://${eureka.instance.ipAddress}:${server.port}${server.servlet.context-path:}/actuator/health
    status-page-url: http://${eureka.instance.ipAddress}:${server.port}${server.servlet.context-path:}/actuator/info
    homePageUrl: http://uapay.uarocky.com/
  client:
    serviceUrl:
      defaultZone: http://payment.uarocky.com:8761/eureka/

feign:
  hystrix:
    enabled: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://dingyue.mysql.database.azure.com:3306/renren_security?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: QQYD_dingyue@dingyue
      password: DU2g_Q@ayHI$
      initial-size: 1
      min-idle: 100
      max-active: 300
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 1
    host: dingyue.redis.cache.windows.net
    port: 6380
    password: gAr7FJWVK9MXRxpw11TVlDFwF4UhPw6VWaKilO78z+c= # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    ssl: true
    jedis:
      pool:
        max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

ph:
  sm:
    sp_password: 0lS90z2h
    sub_url: http://203.87.166.59:8312/1/smsmessaging/outbound/5840/requests
    notify_url: http://rpsmapi.uarocky.com/renren-api/ph/notify/client/delivery/status/json
    server_id: 0064092000011854 #0064092000011854
    product_id: 1000030361 #1000015904 1000015927 1000016205
  wap:
    server_id: 0064092000011854
    sub_url: http://203.87.166.59:8310/SubscribeManageService/services/SubscribeManage
    product_id: 1000030361 #1000015884 1000015927 1000016205
    notify_url: rpsmapi.uarocky.com/renren-api/ph/sync/sms/order/relation


th:
  user: RockyMobi
  password: RockyMobi
  cpId: 3017
  serviceId: 3017001
  sub_url: http://isag.cat3g.com/api/api.otp.gw.php
  sms_url: http://cp.server.com/recv.dr.php
  sms_sussd_url: http://isag.cat3g.com/api/api.smsussd.php

kh:
  cellcard:
    sdp_author_url: https://api-jwt.fortumo.io/authorisations
    sdp_payment_url: https://api-jwt.fortumo.io/payments
    sp_payment_callback_url: https://rpsmapi.uarocky.com/renren-api/cambodia/wap/paymentsCallback
    sp_pin_callback_url: https://rpsmapi.uarocky.com/renren-api/cambodia/wap/getPINCallBack
    sp_he_callback_url: https://rpsmapi.uarocky.com/renren-api/cambodia/wap/getHECallBack
    sp_merchant_id: 05845cae3eb2470c6e2ced320b253921
    sdp_refunds_url: https://api-jwt.fortumo.io/refunds
    sp_refunds_callback_url: https://rpsmapi.uarocky.com/renren-api/cambodia/wap/unsub/refundsCallBack
    sdp_sending_messages_url: https://messaging-jwt.fortumo.io/messaging
    sp_sending_messages_callback_url: https://rpsmapi.uarocky.com/renren-api/cambodia/sms/smsCallback
    sp_unsub_callback_url: https://rpsmapi.uarocky.com/renren-api/cambodia/wap/unsub/terminateCallBack