eureka:
  instance:
    preferIpAddress: true
    ipAddress: 119.3.19.234
    instance-id: http://${eureka.instance.ipAddress}/renren-api/
    health-check-url: http://${eureka.instance.ipAddress}:${server.port}${server.servlet.context-path:}/actuator/health
    status-page-url: http://${eureka.instance.ipAddress}:${server.port}${server.servlet.context-path:}/actuator/info
    home-page-url: http://${eureka.instance.ipAddress}:${server.port}${server.servlet.context-path:}
    metadata-map:
      configPath: ${server.servlet.context-path:}
      management:
        context-path: ${server.servlet.context-path:}
  client:
    serviceUrl:
      defaultZone: http://panshi:panshi@119.3.19.234/uarocky-eureka/eureka/

feign:
  hystrix:
    enabled: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.40.184:3306/uarocky_smsc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root123456
      initial-size: 1
      min-idle: 5
      max-active: 500
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 1
    host: 192.168.0.168
    port: 63799
    password: redis123456 # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    ssl: false
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接